# Generated by Django 4.2 on 2023-05-10 05:17

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('photo', models.FileField(upload_to='Gallery')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('gallery_type', models.CharField(choices=[('Main Gallery', 'Main Gallery'), ('Student Gallery', 'Student Gallery')], max_length=100)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
